### ISSUE TITLE
Parse error while reading token `DELIM

### ISSUE THREAD

**Issue by dylanirlbeck** [astrada/ocaml-css-parser#4]
First of all, thanks for this great tool! I'm using it in an upcoming PPX and so far it's been amazing. I'm very close to releasing my project to the rest of the world 😄 

I'm currently getting the following error while parsing a CSS file:
<img width="367" alt="Screen Shot 2020-04-21 at 5 11 42 PM" src="https://user-images.githubusercontent.com/35497479/79919319-c3978480-83f3-11ea-889f-4b53ac315949.png">

What I believe is the offending CSS:

```css
.space-y-0 > :not(template) ~ :not(template) {
  --space-y-reverse: 0;
  margin-top: calc(0 * calc(1 - var(--space-y-reverse)));
  margin-bottom: calc(0 * var(--space-y-reverse));
}
```

Do you have any ideas on what can be done? Thanks in advance!
