### ISSUE TITLE
Disambiguate pseudo-classes

### ISSUE THREAD

**Issue by Chimrod** [astrada/ocaml-css-parser#8]
css-parser does not seems to be able to differentiate thoses two selectors :

```css
p:first-child {
  color: red;
}
p :first-child {
  color: blue;
} 
```

The first one should apply to the first `<p>` element, while the second only apply the first sub-element in `<p>` 

```html
<!DOCTYPE html>
<html>
<head>
<style>
p:first-child {
  color: red;
} 
p :first-child {
  color: blue;
} 
</style>
</head>
<body>

<p>I am a <i>blue</i> word. I am a <i>red</i> word.</p>
<p>I am a <i>blue</i> word. I am a <i>black</i> word.</p>

</body>
</html>
```

Is there something I've missed ?
